### ISSUE TITLE
没有找到cvMatRepresentationColor

### ISSUE THREAD

**Issue by coooliang** [edisongz/opencv_demo#1]
您好，cvMatRepresentationColor 方法是哪里的呢 UIImage+OpenCV么？
能上传一下么 谢谢咯

**Comment by edisongz** [comment]
opencv2.framework太大了，就没传了，可以上github下载后自己编译；编译后会生成iOS demo。
可以参考：
https://github.com/opencv/opencv  (下载地址)
https://docs.opencv.org/2.4/doc/tutorials/ios/image_manipulation/image_manipulation.html#opencviosimagemanipulation
